version: '3.8'

 livekit:
    image: livekit/livekit-server:latest
    command: ["/livekit-server", "--config", "/etc/livekit.yaml"]
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    restart: unless-stopped
    networks:
      - livekit-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - livekit-network

volumes:
  redis_data:

networks:
  livekit-network:
    driver: bridge
